// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf9J9KGzT1aGq8aDJUzEo_LZ4lMiCzrB8',
    appId: '1:4551239364:web:d1f8a5b6c2e3f4a5b6c7d8',
    messagingSenderId: '4551239364',
    projectId: 'deineputzcrew-8414d',
    storageBucket: 'deineputzcrew-8414d.firebasestorage.app',
    authDomain: 'deineputzcrew-8414d.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf9J9KGzT1aGq8aDJUzEo_LZ4lMiCzrB8',
    appId: '1:4551239364:android:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '4551239364',
    projectId: 'deineputzcrew-8414d',
    storageBucket: 'deineputzcrew-8414d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf9J9KGzT1aGq8aDJUzEo_LZ4lMiCzrB8',
    appId: '1:4551239364:ios:14dc42e8d4fe6fe58a0b91',
    messagingSenderId: '4551239364',
    projectId: 'deineputzcrew-8414d',
    storageBucket: 'deineputzcrew-8414d.firebasestorage.app',
    iosBundleId: 'com.diveinpuits.diveinpuits',
  );
}